const oldCalculation = document.getElementById("oc").innerText;
const currentCalculation = document.getElementById("cc").innerText;
const btn1 = document.getElementById("1");
const btn2 = document.getElementById("2");
const btn3 = document.getElementById("3");
const btn4 = document.getElementById("4");
const btn5 = document.getElementById("5");
const btn6 = document.getElementById("6");
const btn7 = document.getElementById("7");
const btn8 = document.getElementById("8");
const btn9 = document.getElementById("9");
const btn0 = document.getElementById("0");
const btnPlus = document.getElementById("plus");
const btnMinus = document.getElementById("minus");
const btnMultiply = document.getElementById("multiply");
const btnDivide = document.getElementById("divide");
const btnSwap = document.getElementById("swap");
const btnDot = document.getElementById("dot");
const btnClear = document.getElementById("ac");
const btnEnter = document.getElementById("enter");

let displayValue;
